apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.fullname" . }}
  labels:
    app: {{ include "demo-app.name" . }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
    app: {{ include "demo-app.name" . }}
  ports:
    - port: {{ default 80 .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
